version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: production_tutos_nginx
    tmpfs:
      - /etc/nginx/logs
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./.output:/app/.output
    ports:
      - 80:80
