version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.8

executors:
  node:
    parameters:
      node-version:
        # renovate datasource=node-version depName=node
        default: 20.17.0
        type: string
    docker:
      - image: cimg/node:<<parameters.node-version>>
  playwright:
    parameters:
      playwright-version:
        # renovate datasource=npm depName=@playwright/test
        default: 1.48.1
        type: string
    docker:
      - image: mcr.microsoft.com/playwright:v<<parameters.playwright-version>>
    resource_class: medium

jobs:
  test:
    executor: node
    steps:
      - checkout
      - run: cat package*.json > cachekey
      - restore_cache:
          keys:
            - pix-tutos-npm-{{ checksum "cachekey" }}
      - run: npm ci
      - save_cache:
          key: pix-tutos-npm-{{ checksum "cachekey" }}
          paths:
            - ~/.npm
      - run:
          name: Lint
          command: |
            npm run lint
      - run:
          name: Test
          command: |
            npm run test

  e2e:
    executor: playwright
    steps:
      - checkout
      - run: cat package*.json > cachekey
      - restore_cache:
          keys:
            - v2-pix-tutos-e2e-npm-{{ checksum "cachekey" }}
      - run: npm ci
      - run: npm run test:e2e:install
      - save_cache:
          key: v2-pix-tutos-e2e-npm-{{ checksum "cachekey" }}
          paths:
            - ~/.npm
            - ~/.cache/ms-playwright
      - run:
          name: Run E2E tests
          environment:
            PLAYWRIGHT_JUNIT_OUTPUT_NAME: test-results/e2e-junit-results.xml
          command: npm run test:e2e:run -- --reporter=junit
      - store_test_results:
          path: test-results/

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - e2e
