---
version: 2.0

jobs:
  test:
    docker:
      - image: cimg/node:19.6.1
    steps:
      - checkout
      - run: cat package*.json > cachekey
      - restore_cache:
          keys:
            - pix-tutos-npm-{{ checksum "cachekey" }}
      - run: npm ci
      - save_cache:
          key: pix-tutos-npm-{{ checksum "cachekey" }}
          paths:
            - ~/.npm
      - run:
          name: Lint
          command: |
            npm run lint
      - run:
          name: Test
          command: |
            npm run test

  e2e:
    docker:
      - image: mcr.microsoft.com/playwright:v1.31.0-focal
    resource_class: medium
    steps:
      - checkout
      - run: cat package*.json > cachekey
      - restore_cache:
          keys:
            - v2-pix-tutos-e2e-npm-{{ checksum "cachekey" }}
      - run: npm ci
      - run: npm run test:e2e:install
      - save_cache:
          key: v2-pix-tutos-e2e-npm-{{ checksum "cachekey" }}
          paths:
            - ~/.npm
            - ~/.cache/ms-playwright
      - run:
          name: Run E2E tests
          environment:
            PLAYWRIGHT_JUNIT_OUTPUT_NAME: test-results/e2e-junit-results.xml
          command: npm run test:e2e:run -- --reporter=junit
      - store_test_results:
          path: test-results/

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - e2e
