name: automerge check

on:
  pull_request:
    types:
      - labeled
      - unlabeled
  check_suite:
    types:
      - completed
  status:
    types:
      - success

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Automerge has been deactivated on pix-tutos, please use native GitHub Merge button'
      - run: exit 1
